FROM node:latest AS build-env
WORKDIR /app

COPY angularapp/package.json .
COPY angularapp/angular.json .
COPY angularapp/tsconfig.json .
RUN npm install -g @angular/cli --force
RUN npm install --production --force

COPY angularapp/src ./src
COPY angularapp/tsconfig.app.json .
WORKDIR /app
RUN npm install --save-dev @angular-devkit/build-angular
RUN npm run build --prod

FROM nginx:latest

COPY nginx.conf /etc/nginx/nginx.conf
WORKDIR /usr/share/nginx/html
COPY --from=build-env /app/dist/angularapp .

EXPOSE 4200

CMD ["nginx", "-g", "daemon off;"]