FROM node:14.3-slim AS build-env
WORKDIR /app

COPY ./angularapp .
EXPOSE 4200

WORKDIR /app
RUN npm install -g @angular/cli && npm install


RUN ls -al
ENTRYPOINT [ "ng", "serve", "--host", "0.0.0.0", "--poll", "1000"]